[decode-syseeprom] fix getattribute check for sime platforms (#835)
For some platforms which implement the eeprom plugin by inheriting from TlvInfoDecoder, the line

t.getattr('read_eeprom_db', None) == None:
results in an error:
AttributeError: 'board' object has no attribute 'getattr'

The cause for that is that TlvInfoDecoder inherits from object, and looks like for object and derived classes there is no __getattr__.

Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>